/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoupletherapyIndexRouteImport } from './routes/coupletherapy.index'
import { Route as CoupletherapySplatRouteImport } from './routes/coupletherapy.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupletherapyIndexRoute = CoupletherapyIndexRouteImport.update({
  id: '/coupletherapy/',
  path: '/coupletherapy/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupletherapySplatRoute = CoupletherapySplatRouteImport.update({
  id: '/coupletherapy/$',
  path: '/coupletherapy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coupletherapy/$': typeof CoupletherapySplatRoute
  '/coupletherapy/': typeof CoupletherapyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coupletherapy/$': typeof CoupletherapySplatRoute
  '/coupletherapy': typeof CoupletherapyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coupletherapy/$': typeof CoupletherapySplatRoute
  '/coupletherapy/': typeof CoupletherapyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coupletherapy/$' | '/coupletherapy/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coupletherapy/$' | '/coupletherapy'
  id: '__root__' | '/' | '/coupletherapy/$' | '/coupletherapy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoupletherapySplatRoute: typeof CoupletherapySplatRoute
  CoupletherapyIndexRoute: typeof CoupletherapyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupletherapy/': {
      id: '/coupletherapy/'
      path: '/coupletherapy'
      fullPath: '/coupletherapy/'
      preLoaderRoute: typeof CoupletherapyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupletherapy/$': {
      id: '/coupletherapy/$'
      path: '/coupletherapy/$'
      fullPath: '/coupletherapy/$'
      preLoaderRoute: typeof CoupletherapySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoupletherapySplatRoute: CoupletherapySplatRoute,
  CoupletherapyIndexRoute: CoupletherapyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
